apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zookeeper
  namespace: kafka
spec:
  interval: 5m
  chart:
    spec:
      chart: zookeeper
      version: 12.1.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    replicaCount: 3
